envs:
- JACOCO_INSTRUCTION_COVERAGE: 29.14%
- JACOCO_BRANCH_COVERAGE: 24.30%
- JACOCO_LINE_COVERAGE: 31.35%
- JACOCO_COMPLEXITY_COVERAGE: 23.03%
- JACOCO_METHOD_COVERAGE: 26.92%
- JACOCO_CLASS_COVERAGE: 28.17%
